### ISSUE TITLE
打开项目报错

### ISSUE THREAD

**Issue by anyechushang** [UnityTech/ConnectAppCN#263]
unity：2018.4.6f1； Windows平台
下载完项目，导入UIWidgets,，刚开始有一些其他的错误，删除无用的包后就剩这一个错误
Assembly has reference to non-existent assembly 'Windows.UI.Input.Spatial' (Packages/com.unity.xr.legacyinputhelpers/Runtime/LegacyInputHelpers.asmdef)

**Comment by zhuxingwei** [comment]
ConnectApp目前是在Unity2019.1.14f1上开发和维护的，因此其引用到的一些包可能与2018版本不兼容。解决方案是：请使用Unity2019.1.14f1打开项目；或者也可以直接删掉Packages/manifest.xml里面的对应的xr.legacyinputhelpers等引用

**Comment by young1048** [comment]
使用Unity 2019.2.9f1 版本打开项目报错，缺少UIWidgets 和 RSG库：
![报错截图](https://upload-images.jianshu.io/upload_images/2382020-e52b218011f6a49c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by finnif** [comment]
> 使用Unity 2019.2.9f1 版本打开项目报错，缺少UIWidgets 和 RSG库：
> ![报错截图](https://camo.githubusercontent.com/2427ae8000dd7e990f173b973c4465cac51f308a/68747470733a2f2f75706c6f61642d696d616765732e6a69616e7368752e696f2f75706c6f61645f696d616765732f323338323032302d653532623231383031316636613439632e706e673f696d6167654d6f6772322f6175746f2d6f7269656e742f7374726970253743696d61676556696577322f322f772f31323430)

是不是没有更新 submodule，可以尝试更新下。
```
$ cd ConnectAppCN/
$ git submodule init
$ git submodule update
```

**Comment by young1048** [comment]
嗯嗯嗯是的，谢谢




| |
余勇
|
|
邮箱：younggithub@163.com
|

签名由 网易邮箱大师 定制

在2019年10月21日 14:35，wangshuang 写道：

使用Unity 2019.2.9f1 版本打开项目报错，缺少UIWidgets 和 RSG库：


是不是没有更新 submodule，可以尝试更新下。

$ cd ConnectAppCN/

$ git submodule init

$ git submodule update

**Comment by finnif** [comment]
@young1048 如果没有问题的话，我们稍后把 issue close 掉。

**Comment by young1048** [comment]
好的




| |
余勇
|
|
邮箱：younggithub@163.com
|

签名由 网易邮箱大师 定制

在2019年10月22日 17:02，wangshuang 写道：

Closed #263.

**Comment by plmkojx** [comment]
git 拉下来太慢了,不能一起上传吗,我下载zip包能直接跑的,谢谢了

**Comment by finnif** [comment]
> git 拉下来太慢了,不能一起上传吗,我下载zip包能直接跑的,谢谢了

可以下载 UIWidgets 的 zip 包解压到 ConnectAppCN/Packages/ 目录下

**Comment by plmkojx** [comment]
> > git 拉下来太慢了,不能一起上传吗,我下载zip包能直接跑的,谢谢了
> 
> 可以下载 UIWidgets 的 zip 包解压到 ConnectAppCN/Packages/ 目录下

好了,packages下原来可以直接放入工程,学习了,3q!

**Comment by plmkojx** [comment]
> > git 拉下来太慢了,不能一起上传吗,我下载zip包能直接跑的,谢谢了
> 
> 可以下载 UIWidgets 的 zip 包解压到 ConnectAppCN/Packages/ 目录下

Refresh case sensitivity failure. Asset: Packages/com.unity.uiwidgets/scripts ; Metafile: Packages/com.unity.uiwidgets/scripts.meta
现在有个这么红色报错一直刷
