### ISSUE TITLE
使用Mac版本UnityHub，项目工程无法正常打开

### ISSUE THREAD

**Issue by actionmoon** [UnityTech/ConnectAppCN#356]
使用Mac  版本的 UnityHub 打开工程， Unity版本2019.1.14f1 ，Add Project 之后点击ConnectAppCN，打开，没反应！

**Comment by actionmoon** [comment]
问题已经解决，ProjectSettings/ProjectVersion.txt 需要提交GitHub，否则UnityHub并不知道使用哪个版本Unity去打开项目工程（因为Unity工程兼容和升级）

**Comment by actionmoon** [comment]
在.gitignore文件中发现ProjectSettings/ProjectVersion.txt忽略提交
# Unity3D generated file on crash reports
sysinfo.txt
ProjectSettings/ProjectVersion.txt

不知道是什么原因！

**Comment by finnif** [comment]
谢谢反馈，这样做的原因是为了规避如果上传了高版本的版本信息，会导致低版本的用户打开出问题。我们想的是如果没有版本信息，可以在 Unity Hub 上选择版本， Editor 会自己生成 ProjectVersion.txt。如果您有更好的办法和建议，欢迎提出来。

**Comment by finnif** [comment]
如果没有其他问题的话，我先关闭这个 issue。
