### ISSUE TITLE
安卓真机白屏

### ISSUE THREAD

**Issue by setsuodu** [UnityTech/ConnectAppCN#544]
华为H8真机，夜神模拟器。
Unity2018.4.0f1, Unity2018.4.10f1, Unity2019.3.3f1, Unity2019.3.4f1, 用以上版本测试了。
v1.5.4-preview.6以下是正常的，preview.7~12都白屏，只渲染了 RawImage。

另外在previwe.12测试有这样的问题。
void setAlias() 函数参数在不同平台不同。
namespace name 'AnimatedPositioned' could not be found。
'SliverFillRemaining' is inaccessible due to its protection level。

**Comment by finnif** [comment]
Duplicate of #558
