### ISSUE TITLE
unity 2018.4 2019.3 打开都报错,求解

### ISSUE THREAD

**Issue by crazysnowboy** [UnityTech/ConnectAppCN#548]
Assets/ConnectApp/Plugins/JPushPlugin.cs(389,13): error CS1501: No overload for method 'deleteAlias' takes 2 arguments

**Comment by finnif** [comment]
这个 issue 应该已经修好了，可以重新按照 readme 再运行一遍

**Comment by finnif** [comment]
Duplicate of #558
