### ISSUE TITLE
error CS0234

### ISSUE THREAD

**Issue by AndyWangGoGoGo** [UnityTech/ConnectAppCN#549]
Packages\com.unity.uiwidgets\Runtime\engine\input_utils.cs(3,19): error CS0234: The type or namespace name 'EventSystems' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
Packages\com.unity.uiwidgets\Runtime\engine\UIWidgetsPanel.cs(11,30): error CS0234: The type or namespace name 'UI' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?)
…………………………
Unity2019.2.21f1

**Comment by weidiaoxiang** [comment]
Got same issue with latest unity 2019.3.6f1.

**Comment by finnif** [comment]
可以在根目录试试 
```shell
git submodule init && git submodule update
```

**Comment by finnif** [comment]
Duplicate of #558
